apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: duhehrw5d-nodejs 
  janus-idp.io/tekton: duhehrw5d-nodejs
  backstage.io/kubernetes-id: duhehrw5d-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: duhehrw5d-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml